aws_region           = "eu-west-1"
environment          = "production"
ec2_key_name         = "my-key"
instance_type        = "t3.medium"
db_username          = "produser"
db_password          = "super-secure-password"
db_instance_class    = "db.t4g.medium"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.11.0/24", "10.0.12.0/24"]
az_count             = 2
